### ISSUE TITLE
NPE when asking for call time of non-existent party.

### ISSUE THREAD

**Issue by bwhitneyXima** [wendelicious/call-monitor#1]
Looks like there's a null pointer being thrown when running test00. In this case it's asking for the call time of a party that hasn't ever actually had any calls.

```
java.lang.NullPointerException
	at com.ximasoftware.persistence.CallTimeTracker.countCalltimeForParty(CallTimeTracker.java:45)
	at com.ximasoftware.persistence.CallEventPersistence.getTotalCallTimeForParty(CallEventPersistence.java:100)
	at com.ximasoftware.impl.CallDataHandlerImpl.getTotalCallTimeForParty(CallDataHandlerImpl.java:49)
	at com.ximasoftware.TestCallDataHandler.test00(TestCallDataHandler.java:24)
...
```

**Comment by wendelicious** [comment]
Fascinating.  The tests passed for me both in IntelliJ and Eclipse. I'll look at this again and see what is going on here.  Thanks!

**Comment by wendelicious** [comment]
Good catch. The worst shame is the NPE.

**Comment by bwhitneyXima** [comment]
Hey thanks for fixing that!
